---
title: "R-club-April 26"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> 3.2.4 Exercises
> Q1

```{r, warning=FALSE}
library(tidyverse)
library(ggplot2)

mpg

ggplot(data = mpg)

#no plot was generated. 
#234 rows, 11 columns.

?mpg

#drv: drv. f = front-wheel drive, r = rear wheel drive, 4 = 4wd

ggplot(data = mpg) +
  geom_point(mapping = aes(x = class , y = drv))

#Since both variales are factors, no values. Scatterplot is not helpful. 
```

> 3.3.1 Exercises
> Q1

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = "blue"))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

> Q2

```{r}
?mpg

#Categorical: manufacturer, model, trans, drv, fl, class
#Continuous: displ, year, cyl, cty, hwy
```

> Q3

```{r}

#color
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = cty))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))

#size
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = cty))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))

#shape
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```

> Q4

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class, color = class))
```

> Q5

```{r}
?geom_point

#strock decides the width of edges of shape. 
```

> Q6

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = class, y = hwy, shape = class, color = displ < 5))
```

> 3.5.1
> Q1 

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ cty)

#Too many subplots.
```

> Q2

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = drv, y = cyl))
```

> Q3

```{r}

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)
```

> Q4

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
```

> Q5

```{r}
?facet_wrap
#to separate subplots into rows/columns we need
#since the rows and columns decided by the number of data in the variables. 
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(cyl~drv)
```

