---
title: "R-club-May-17"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nycflights13)
library(tidyverse)
```

```{r}
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))

by_dest <- group_by(flights, dest)
delay <- summarise(by_dest,
  count = n(),
  dist = mean(distance, na.rm = TRUE),
  delay = mean(arr_delay, na.rm = TRUE)
)

delay <- filter(delay, count > 20, dest != "HNL")

ggplot(data = delay, mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)

delays <- flights %>% 
  group_by(dest) %>% 
  summarise(
    count = n(),
    dist = mean(distance, na.rm = TRUE),
    delay = mean(arr_delay, na.rm = TRUE)
  ) %>% 
  filter(count > 20, dest != "HNL")
```

Q 5.6.7
```{r}
#1. 
not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))



#2. 
not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>%
  group_by(dest) %>%
  summarise(n())

not_cancelled %>%
  group_by(tailnum) %>%
  summarise(sum(distance))

#3. Not every flight with "NA" in arr_delay was canceled. dep_delay is more important. 


#4. 
cancelled <- flights %>% 
  filter(is.na(dep_time))

cancelled %>%
  group_by(year, month, day) %>%
  summarise(flights = n(), 
            ave_delay = mean(dep_delay, na.rm = TRUE)) 


cancelled <- flights %>% 
  filter(is.na(dep_time))

not_cancelled <- flights %>%
  filter(!is.na(dep_time))

by_day_cancelled <- group_by(cancelled, year, month, day)
by_day_not_cancelled <- group_by(not_cancelled, year, month, day)
total_flights <- group_by(flights, year, month, day)

correlation <- summarise(total_flights, 
    prop_cancelled = n()/sum(n()),
    ave_delay = mean(dep_delay, na.rm = TRUE))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(hour_perc = mean(arr_delay > 60))

#5. 
not_cancelled <- flights %>%
  filter(!is.na(dep_time))

not_cancelled %>%
  group_by(carrier) %>%
  summarise(delay_time = mean(arr_delay > 0 & !is.na(arr_delay))) %>%
  arrange(desc(delay_time))


flights %>% 
  group_by(carrier, dest) %>% 
  summarise(n())

#6. 
count(flights, dest, sort = TRUE)
  
```

Q 5.7.1
```{r}
#1. 

#2. 
flights %>%
  group_by(tailnum) %>%
  summarise(ave_delay_time = mean(arr_delay[arr_delay >0 & !is.na(arr_delay)])) %>%
  arrange(desc(ave_delay_time)) 

#3. 
  flights %>%
  group_by(dep_time) %>% 
  summarise(num_delay = sum(!is.na(arr_delay) & arr_delay > 0)) %>%
  arrange(desc(num_delay))

#4. 
  flights %>%
    group_by(dest) %>%
    summarise(minute = sum(arr_delay, na.rm = TRUE))
  
  flights %>%
    group_by(tailnum) %>%
    summarise(prop_delay = mean(arr_delay > 0, na.rm = TRUE))
  
#5. 
lag(flights$dep_delay)
  

#6. 

#7. 
 flights %>%
     group_by(dest) %>%
     count(carrier) %>%
   summarise(num_carrier = n()) %>%
   filter(num_carrier > 1) %>%
   arrange()

#8. 
```

